name: Code Formatting Check

on: [push, pull_request]

jobs:
  format-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Specify your Node.js version
      
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install
      
      - name: Run Frontend Prettier Check
        run: |
          cd frontend
          npm run check

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7' # Specify your Python version

      - name: Install Backend Dependencies
        run: |
          cd backend
          pip install -r requirements.txt
      
      - name: Run Backend Black Check
        run: |
          cd backend
          black --check .
